Reinitialize `Engine.context` after resetting `Engine`
Since `Engine.reset` deletes the `context` attribute, `__del__` raises the following exception:
`AttributeError: 'Engine' object has no attribute 'context'`

This commit fixes `Engine.reset` by reinitializing the `context` attribute to avoid this error.